# Generated by Django 4.2.6 on 2023-10-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SolarYield",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(default="de", max_length=3)),
                ("date", models.DateField()),
                ("zip_code_suffix", models.SmallIntegerField()),
                ("zip_code_prefix", models.SmallIntegerField()),
                ("year", models.SmallIntegerField()),
                (
                    "band",
                    models.CharField(
                        choices=[
                            ("LO", "Low"),
                            ("MI", "Mid"),
                            ("HI", "High"),
                            ("UP", "Upper"),
                        ],
                        max_length=2,
                    ),
                ),
                ("value", models.FloatField()),
            ],
        ),
    ]
