# Generated by Django 4.2.6 on 2023-10-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solar", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="solaryield",
            name="state",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
